import {act,cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import App from './App';
const control=vi.hoisted(()=>({defer:'', resolve:null as null|((v:unknown)=>void),reject:null as null|((v:unknown)=>void),calls:[] as string[]}));
const pool={id:'pool',name:'平台 A',official:{prefix:'https://example.com/join/',suffix:''},candidates:[{id:'c',prefix:'https://example.org/join/',suffix:'',enabled:true}],updated:'2026-09-30',accountIds:[]};
const state={accounts:[{id:'a',label:'账户 A',zoneCount:1,checkedAt:null,hasResources:true,needsSelftestKey:false}],domains:[{id:'d',accountId:'a',zoneId:'z',host:'go.example.com',prefix:'r',routeId:'r'}],links:[],pools:[pool],pendingOperations:[],pendingActions:[]};
const plan=(title='保存短链接')=>({id:'p',title,steps:['保存'],warnings:[],expiresAt:new Date(Date.now()+300000).toISOString()});
vi.mock('./bridge',()=>({preview:true,errorMessage:(e:unknown)=>String(e),dispatch:async(action:string)=>{
 control.calls.push(action);
 if(action===control.defer)return new Promise((resolve,reject)=>{control.resolve=resolve;control.reject=reject;});
 if(action==='get_state'||action==='apply_plan'||action==='import_token')return state;
 if(action==='prepare_change')return plan();
 if(action==='check_update')return {status:'available',currentVersion:'0.1.7',version:'0.1.8'};
 if(action==='token_template')return '';
 throw Error(action);
}}));
afterEach(()=>{cleanup();vi.restoreAllMocks();control.defer='';control.resolve=null;control.reject=null;control.calls=[];});
async function start(){render(<App/>);await waitFor(()=>expect(screen.queryByText('正在读取本机配置…')).toBeNull());}
async function linkEditor(slug:string){fireEvent.click(screen.getAllByRole('button',{name:'新建链接'})[0]);const d=screen.getByRole('dialog',{name:'创建短链接'});fireEvent.change(within(d).getByPlaceholderText('例如 welcome'),{target:{value:slug}});fireEvent.change(within(d).getByPlaceholderText('https://example.com/zh'),{target:{value:'https://example.com/zh'}});fireEvent.change(within(d).getByPlaceholderText('https://example.com/en'),{target:{value:'https://example.com/en'}});return d;}
it('active remote apply must prevent dismissing the confirmation and losing a subsequent draft',async()=>{
 control.defer='apply_plan';await start();const editor=await linkEditor('first');fireEvent.click(within(editor).getByRole('button',{name:'下一步，核对内容'}));const review=await screen.findByRole('dialog',{name:'保存短链接'});fireEvent.click(within(review).getByRole('button',{name:'确认并执行'}));await waitFor(()=>expect(control.resolve).toBeTruthy());
 expect((within(review).getByRole('button',{name:'返回'}) as HTMLButtonElement).disabled).toBe(true);
});
it('keeps an executing plan open through Cancel, Escape and backdrop attempts',async()=>{
 control.defer='apply_plan';await start();const editor=await linkEditor('first');fireEvent.click(within(editor).getByRole('button',{name:'下一步，核对内容'}));const review=await screen.findByRole('dialog',{name:'保存短链接'});fireEvent.click(within(review).getByRole('button',{name:'确认并执行'}));await waitFor(()=>expect(control.resolve).toBeTruthy());fireEvent.click(within(review).getByRole('button',{name:'返回'}));fireEvent.keyDown(document,{key:'Escape'});fireEvent.mouseDown(review.parentElement!);expect(screen.getByRole('dialog',{name:'保存短链接'})).toBe(review);fireEvent.click(within(review).getByRole('button',{name:'正在提交…'}));expect(control.calls.filter(a=>a==='apply_plan')).toHaveLength(1);await act(async()=>control.resolve?.(state));expect(screen.queryByRole('dialog')).toBeNull();
});
it('cancelled monitor preparation must not reopen a confirmation from its late result',async()=>{
 control.defer='prepare_monitor';await start();fireEvent.click(screen.getByRole('button',{name:'Cloudflare 账户'}));fireEvent.click(screen.getByRole('button',{name:'管理 账户 A'}));fireEvent.click(screen.getByRole('button',{name:'配置检测服务'}));const editor=screen.getByRole('dialog',{name:'配置检测服务'});fireEvent.change(within(editor).getByPlaceholderText('https://probe.example.com/check'),{target:{value:'https://probe.example.com/check'}});fireEvent.change(within(editor).getByLabelText(/服务密钥/),{target:{value:'X'.repeat(40)}});fireEvent.click(within(editor).getByRole('button',{name:'预览启用计划'}));await waitFor(()=>expect(control.resolve).toBeTruthy());fireEvent.click(within(editor).getByRole('button',{name:'取消'}));await act(async()=>control.resolve?.(plan('启用检测服务')));
 expect(screen.queryByRole('dialog')).toBeNull();
});
it('server platform preparation errors must be visible inside its open editor',async()=>{
 control.defer='prepare_change';await start();fireEvent.click(screen.getByRole('button',{name:'平台地址'}));fireEvent.click(screen.getByRole('button',{name:'编辑地址'}));const editor=screen.getByRole('dialog',{name:'编辑平台地址'});fireEvent.click(within(editor).getByRole('button',{name:'下一步，核对内容'}));await waitFor(()=>expect(control.reject).toBeTruthy());await act(async()=>control.reject?.(new Error('平台存在未完成同步，请先恢复')));
 expect(within(editor).queryByRole('alert')?.textContent).toContain('平台存在未完成同步，请先恢复');
 fireEvent.click(within(editor).getByRole('button',{name:'取消'}));fireEvent.click(screen.getByRole('button',{name:'添加平台地址'}));expect(within(screen.getByRole('dialog',{name:'添加平台地址'})).queryByRole('alert')).toBeNull();
});
it('returns a failed platform apply to its unchanged draft with a visible server error',async()=>{
 control.defer='apply_plan';await start();fireEvent.click(screen.getByRole('button',{name:'平台地址'}));fireEvent.click(screen.getByRole('button',{name:'编辑地址'}));let editor=screen.getByRole('dialog',{name:'编辑平台地址'});fireEvent.click(within(editor).getByRole('button',{name:'下一步，核对内容'}));const review=await screen.findByRole('dialog',{name:'保存短链接'});fireEvent.click(within(review).getByRole('button',{name:'确认并执行'}));await waitFor(()=>expect(control.reject).toBeTruthy());await act(async()=>control.reject?.(Error('同步失败，请核对账户')));editor=screen.getByRole('dialog',{name:'编辑平台地址'});expect(within(editor).getByRole('alert').textContent).toContain('同步失败，请核对账户');expect((within(editor).getByPlaceholderText('例如：常用平台 A') as HTMLInputElement).value).toBe('平台 A');fireEvent.change(within(editor).getByPlaceholderText('例如：常用平台 A'),{target:{value:'修订平台'}});expect(within(editor).queryByRole('alert')).toBeNull();
});
async function prepareMonitor(){
 control.defer='prepare_monitor';await start();fireEvent.click(screen.getByRole('button',{name:'Cloudflare 账户'}));fireEvent.click(screen.getByRole('button',{name:'管理 账户 A'}));fireEvent.click(screen.getByRole('button',{name:'配置检测服务'}));const editor=screen.getByRole('dialog',{name:'配置检测服务'});fireEvent.change(within(editor).getByPlaceholderText('https://probe.example.com/check'),{target:{value:'https://probe.example.com/check'}});fireEvent.change(within(editor).getByLabelText(/服务密钥/),{target:{value:'X'.repeat(40)}});fireEvent.click(within(editor).getByRole('button',{name:'预览启用计划'}));await waitFor(()=>expect(control.resolve).toBeTruthy());return editor;
}
it('ignores monitor preparation after fields change and retains the edited secret',async()=>{
 const editor=await prepareMonitor();fireEvent.change(within(editor).getByLabelText(/服务密钥/),{target:{value:'Y'.repeat(40)}});await act(async()=>control.resolve?.(plan('旧检测配置')));expect(screen.queryByRole('dialog',{name:'旧检测配置'})).toBeNull();expect((within(editor).getByLabelText(/服务密钥/) as HTMLInputElement).value).toBe('Y'.repeat(40));
});
it('does not inject a cancelled monitor request error into a newly opened form',async()=>{
 const editor=await prepareMonitor();fireEvent.click(within(editor).getByRole('button',{name:'取消'}));fireEvent.click(screen.getByRole('button',{name:'管理 账户 A'}));fireEvent.click(screen.getByRole('button',{name:'配置检测服务'}));const reopened=screen.getByRole('dialog',{name:'配置检测服务'});fireEvent.change(within(reopened).getByLabelText(/服务密钥/),{target:{value:'Y'.repeat(40)}});await act(async()=>control.reject?.(Error('旧检测配置失败')));expect(within(reopened).queryByRole('alert')).toBeNull();expect((within(reopened).getByLabelText(/服务密钥/) as HTMLInputElement).value).toBe('Y'.repeat(40));
});
it('keeps token import locked even when a separate template request finishes',async()=>{
 control.defer='import_token';await start();fireEvent.click(screen.getByRole('button',{name:'Cloudflare 账户'}));fireEvent.click(screen.getByRole('button',{name:'导入账户'}));const editor=screen.getByRole('dialog',{name:'导入访问令牌'});fireEvent.change(within(editor).getByPlaceholderText('在此粘贴令牌'),{target:{value:'old-token'}});fireEvent.submit(editor.querySelector('form')!);await waitFor(()=>expect(control.resolve).toBeTruthy());await act(async()=>fireEvent.click(within(editor).getByRole('button',{name:'在系统浏览器中打开令牌模板'})));expect((within(editor).getByRole('button',{name:'取消'}) as HTMLButtonElement).disabled).toBe(true);expect((within(editor).getByRole('button',{name:'正在验证…'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.keyDown(document,{key:'Escape'});fireEvent.submit(editor.querySelector('form')!);expect(control.calls.filter(a=>a==='import_token')).toHaveLength(1);await act(async()=>control.resolve?.(state));await waitFor(()=>expect(screen.queryByRole('dialog',{name:'导入访问令牌'})).toBeNull());
});
it('keeps token import locked until clipboard digest postprocessing completes',async()=>{
 let finishDigest:((value:ArrayBuffer)=>void)|undefined;
 vi.spyOn(crypto.subtle,'digest').mockImplementationOnce(()=>new Promise<ArrayBuffer>(resolve=>{finishDigest=resolve;}));
 await start();fireEvent.click(screen.getByRole('button',{name:'Cloudflare 账户'}));fireEvent.click(screen.getByRole('button',{name:'导入账户'}));const editor=screen.getByRole('dialog',{name:'导入访问令牌'});fireEvent.change(within(editor).getByPlaceholderText('在此粘贴令牌'),{target:{value:'old-token'}});fireEvent.submit(editor.querySelector('form')!);await waitFor(()=>expect(finishDigest).toBeTruthy());expect((within(editor).getByRole('button',{name:'取消'}) as HTMLButtonElement).disabled).toBe(true);expect((within(editor).getByRole('button',{name:'正在验证…'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.keyDown(document,{key:'Escape'});expect(screen.getByRole('dialog',{name:'导入访问令牌'})).toBe(editor);await act(async()=>finishDigest?.(new ArrayBuffer(32)));expect(screen.queryByRole('dialog',{name:'导入访问令牌'})).toBeNull();
});
it('prevents pending rename cancellation and duplicate submission, then unlocks after failure',async()=>{
 control.defer='rename_account';await start();fireEvent.click(screen.getByRole('button',{name:'Cloudflare 账户'}));fireEvent.click(screen.getByRole('button',{name:'管理 账户 A'}));fireEvent.click(screen.getByRole('button',{name:'修改本机备注'}));const editor=screen.getByRole('dialog',{name:'重命名账户'});fireEvent.change(within(editor).getByLabelText('账户名称'),{target:{value:'first-name'}});fireEvent.submit(editor.querySelector('form')!);await waitFor(()=>expect(control.resolve).toBeTruthy());expect((within(editor).getByRole('button',{name:'取消'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.keyDown(document,{key:'Escape'});fireEvent.submit(editor.querySelector('form')!);expect(control.calls.filter(a=>a==='rename_account')).toHaveLength(1);await act(async()=>control.reject?.(Error('名称保存失败')));expect(within(editor).getByRole('alert').textContent).toContain('名称保存失败');expect((within(editor).getByRole('button',{name:'取消'}) as HTMLButtonElement).disabled).toBe(false);
});
it('locks local account removal until its failure is handled',async()=>{
 control.defer='remove_account';await start();fireEvent.click(screen.getByRole('button',{name:'Cloudflare 账户'}));fireEvent.click(screen.getByRole('button',{name:'管理 账户 A'}));fireEvent.click(screen.getByRole('button',{name:'从本机移除'}));const editor=screen.getByRole('dialog',{name:'从本机移除账户'});fireEvent.click(within(editor).getByRole('button',{name:'确认本机移除'}));await waitFor(()=>expect(control.resolve).toBeTruthy());expect((within(editor).getByRole('button',{name:'取消'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.keyDown(document,{key:'Escape'});expect(screen.getByRole('dialog',{name:'从本机移除账户'})).toBe(editor);await act(async()=>control.reject?.(Error('移除未完成')));expect(within(editor).getByRole('alert').textContent).toContain('移除未完成');expect((within(editor).getByRole('button',{name:'取消'}) as HTMLButtonElement).disabled).toBe(false);
});
it('locks update installation until its failure is handled',async()=>{
 control.defer='install_update';await start();fireEvent.click(screen.getByRole('button',{name:'检查更新'}));const editor=await screen.findByRole('dialog',{name:'应用更新'});fireEvent.click(within(editor).getByRole('button',{name:'确认安装更新'}));await waitFor(()=>expect(control.resolve).toBeTruthy());expect((within(editor).getByRole('button',{name:'稍后再说'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.keyDown(document,{key:'Escape'});expect(screen.getByRole('dialog',{name:'应用更新'})).toBe(editor);await act(async()=>control.reject?.(Error('安装失败')));expect(within(editor).getByRole('alert').textContent).toContain('安装失败');expect((within(editor).getByRole('button',{name:'稍后再说'}) as HTMLButtonElement).disabled).toBe(false);
});
