import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, describe, expect, it } from 'vitest';
import App from './App';
import userEvent from '@testing-library/user-event';

afterEach(() => cleanup());

describe('desktop primary flows in explicit preview', () => {
  it('keeps focus while typing and accepts a pasted domain URL', async () => {
    const user = userEvent.setup();
    render(<App />);
    await screen.findByText('让每条链接，各有去处。');
    await user.click(screen.getByRole('button', { name: /^域名$/ }));
    await user.click(screen.getByRole('button', { name: '添加域名' }));
    const editor = screen.getByRole('dialog', { name: '添加域名' });
    const input = within(editor).getByPlaceholderText('go.example.com');
    await user.type(input, 'https://WWW.example.com/path');
    expect((input as HTMLInputElement).value).toBe('https://WWW.example.com/path');
    expect(document.activeElement).toBe(input);
    await user.click(within(editor).getByRole('button', { name: '开始检查' }));
    expect(await within(editor).findByText(/检查结果 · www.example.com/)).toBeTruthy();
  });
  it('navigates between four working pages', async () => {
    render(<App />);
    await screen.findByText('让每条链接，各有去处。');
    fireEvent.click(screen.getByRole('button', { name: /^域名$/ }));
    expect(screen.getByText('管理你的链接域名。')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: /^地址池$/ }));
    expect(screen.getByText('一处更新，共享目标。')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: /^账户$/ }));
    expect(screen.getByText('让账户连接井然有序。')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: '检查更新' }));
    const update = await screen.findByRole('dialog', { name: '应用更新' });
    expect(within(update).getByText('更新渠道尚未启用。请使用正式发行渠道获取新版本。')).toBeTruthy();
  });

  it('shows and confirms a prepared plan before changing a link', async () => {
    render(<App />);
    await screen.findByText('让每条链接，各有去处。');
    fireEvent.click(screen.getByRole('button', { name: '新建链接' }));
    const editor = screen.getByRole('dialog', { name: '创建短链接' });
    fireEvent.change(within(editor).getByPlaceholderText('例如 summer'), { target: { value: 'campaign' } });
    fireEvent.change(within(editor).getByPlaceholderText('https://example.com/zh'), { target: { value: 'https://example.com/zh' } });
    fireEvent.change(within(editor).getByPlaceholderText('https://example.com/en'), { target: { value: 'https://example.org/en' } });
    fireEvent.click(within(editor).getByRole('button', { name: '预览变更' }));
    const plan = await screen.findByRole('dialog', { name: '保存短链接' });
    expect(within(plan).getByText('核对当前状态与资源归属')).toBeTruthy();
    expect(document.querySelector('.link-groups')?.textContent).not.toContain('/campaign');
    fireEvent.click(within(plan).getByRole('button', { name: '确认并执行' }));
    await waitFor(() => expect(screen.getByText('/campaign')).toBeTruthy());
    const test = await screen.findByRole('dialog', { name: '链接检测' });
    expect(within(test).getByText('等待传播')).toBeTruthy();
  });
  it('saves a pool reference with an independent code and preserves local unknown detection', async () => {
    render(<App />);
    await screen.findByText('让每条链接，各有去处。');
    fireEvent.click(screen.getByRole('button', { name: /^地址池$/ }));
    fireEvent.click(screen.getByRole('button', { name: '新建地址池' }));
    const pool = screen.getByRole('dialog', { name: '新建共享地址池' });
    fireEvent.change(within(pool).getByPlaceholderText('按用途或平台命名'), {target:{value:'演示地址池'}});
    fireEvent.change(within(pool).getByPlaceholderText('https://example.com/join/'), {target:{value:'https://example.com/join/'}});
    fireEvent.change(within(pool).getByPlaceholderText('https://example.org/join/'), {target:{value:'https://example.org/join/'}});
    fireEvent.click(within(pool).getByRole('button', {name:'预览统一变更'}));
    let poolPlan = await screen.findByRole('dialog', {name:'保存地址池'});
    expect(within(poolPlan).getByText('关联链接：0 条')).toBeTruthy();
    expect(within(poolPlan).getByText('其他地区：https://example.com/join/用户代码')).toBeTruthy();
    fireEvent.click(within(poolPlan).getByRole('button', {name:'返回'}));
    const restored = await screen.findByRole('dialog', {name:'新建共享地址池'});
    expect((within(restored).getByPlaceholderText('按用途或平台命名') as HTMLInputElement).value).toBe('演示地址池');
    fireEvent.click(within(restored).getByRole('button', {name:'预览统一变更'}));
    poolPlan = await screen.findByRole('dialog', {name:'保存地址池'});
    fireEvent.click(within(poolPlan).getByRole('button', {name:'确认并执行'}));
    await waitFor(()=>expect(screen.getByText('演示地址池')).toBeTruthy());
    fireEvent.click(screen.getByRole('button', {name:/^短链接/}));
    fireEvent.click(screen.getByRole('button', {name:'新建链接'}));
    const editor = screen.getByRole('dialog', {name:'创建短链接'});
    fireEvent.change(within(editor).getByPlaceholderText('例如 summer'), {target:{value:'pool-code'}});
    fireEvent.click(within(editor).getByRole('button', {name:'共享地址池'}));
    fireEvent.change(within(editor).getByPlaceholderText('例如 member_01'), {target:{value:'member_01'}});
    fireEvent.click(within(editor).getByRole('button', {name:'预览变更'}));
    const linkPlan = await screen.findByRole('dialog', {name:'保存短链接'});
    expect(within(linkPlan).getByText('用户代码：member_01')).toBeTruthy();
    expect(within(linkPlan).queryByText(/中国大陆：https/)).toBeNull();
    fireEvent.click(within(linkPlan).getByRole('button', {name:'确认并执行'}));
    const result = await screen.findByRole('dialog', {name:'链接检测'});
    expect(within(result).getAllByText(/本地预览未发起网络检测/)).toHaveLength(2);
    fireEvent.click(within(result).getByRole('button', {name:'完成'}));
    expect(screen.getByText('有待确认结果', {exact:false})).toBeTruthy();
    expect(screen.getByText('地址池：演示地址池 · 用户代码：member_01')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', {name:/^地址池$/}));
    fireEvent.click(screen.getByRole('button', {name:'编辑地址池 演示地址池'}));
    const editPool = screen.getByRole('dialog', {name:'编辑共享地址池'});
    fireEvent.change(within(editPool).getByPlaceholderText('https://example.org/join/'), {target:{value:'https://example.org/new/'}});
    fireEvent.click(within(editPool).getByRole('button', {name:'预览统一变更'}));
    const editPlan = await screen.findByRole('dialog', {name:'保存地址池'});
    expect(within(editPlan).getByText('关联链接：1 条')).toBeTruthy();
    fireEvent.click(within(editPlan).getByRole('button', {name:'确认并执行'}));
    await waitFor(()=>expect(screen.queryByRole('dialog', {name:'保存地址池'})).toBeNull());
    fireEvent.click(screen.getByRole('button', {name:/^短链接/}));
    expect(screen.getByText('结果已过期', {exact:false})).toBeTruthy();
    expect(screen.getByText('地址池：演示地址池 · 用户代码：member_01')).toBeTruthy();
  });
  it('prepares optional monitoring without displaying its secret in the plan', async () => {
    render(<App />);
    await screen.findByText('让每条链接，各有去处。');
    fireEvent.click(screen.getByRole('button', {name:/^账户$/}));
    fireEvent.click(screen.getByRole('button', {name:'示例账户 · 团队 更多操作'}));
    fireEvent.click(screen.getByRole('button', {name:'配置检测服务'}));
    const editor = screen.getByRole('dialog', {name:'配置检测服务'});
    fireEvent.change(within(editor).getByPlaceholderText('https://probe.example.com/check'), {target:{value:'https://probe.example.com/check'}});
    fireEvent.change(within(editor).getByLabelText(/服务密钥/), {target:{value:'top-secret-demo-12345678901234567890'}});
    fireEvent.click(within(editor).getByRole('button', {name:'预览启用计划'}));
    const plan = await screen.findByRole('dialog', {name:'启用检测服务'});
    expect(plan.textContent).not.toContain('top-secret-demo');
    expect(plan.textContent).toContain('https://probe.example.com/check');
    fireEvent.click(within(plan).getByRole('button', {name:'确认并执行'}));
    await waitFor(()=>expect(screen.getByText(/检测服务：已启用/)).toBeTruthy());
  });
});
