import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import App from './App';
import userEvent from '@testing-library/user-event';
import * as bridge from './bridge';
import type { Action, DomainPreparation } from './types';

afterEach(() => { cleanup(); vi.restoreAllMocks(); });

describe('desktop primary flows in explicit preview', () => {
  it('shows the existing-page warning, requires scope confirmation, and preserves the draft on return', async () => {
    const originalDispatch = bridge.dispatch;
    const applyPayloads: Record<string, unknown>[] = [];
    const mockedDispatch = (action: Action, payload: Record<string, unknown> = {}): Promise<unknown> => {
      if (action === 'apply_plan') applyPayloads.push(payload);
      return originalDispatch(action, payload);
    };
    vi.spyOn(bridge, 'dispatch').mockImplementation(mockedDispatch as typeof bridge.dispatch);
    const user = userEvent.setup();
    render(<App />);
    await screen.findByRole('heading', {name:'短链接'});
    await user.click(screen.getByRole('button', { name: /^域名管理$/ }));
    await user.click(screen.getByRole('button', { name: '添加域名' }));
    const editor = screen.getByRole('dialog', { name: '添加域名' });
    const input = within(editor).getByPlaceholderText('go.example.com');
    await user.type(input, 'https://WWW.example.com/path');
    expect((input as HTMLInputElement).value).toBe('https://WWW.example.com/path');
    expect(document.activeElement).toBe(input);
    const prefix = within(editor).getByLabelText(/链接目录/);
    await user.clear(prefix);
    await user.type(prefix, 'r');
    await user.click(within(editor).getByRole('button', { name: '检查并接入' }));
    expect(await within(editor).findByText('www.example.com/r/')).toBeTruthy();
    await user.selectOptions(within(editor).getByRole('combobox', { name: /选择账户与区域/ }), 'demo-a');
    expect(within(editor).queryByText('www.example.com/r/')).toBeNull();
    await user.click(within(editor).getByRole('button', { name: '检查并接入' }));
    expect(await within(editor).findByText('确认后可接入')).toBeTruthy();
    expect(within(editor).getByText(/HTTP 200/)).toBeTruthy();
    await user.click(within(editor).getByRole('button', { name: '查看接入计划' }));
    const plan = await screen.findByRole('dialog', { name: '添加 www.example.com' });
    expect(within(plan).getByText(/www\.example\.com\/r\/ 及其所有下级内容/)).toBeTruthy();
    expect(within(plan).getByText(/原该目录内网页将不能继续按原方式访问/)).toBeTruthy();
    expect(within(plan).getByRole('button', { name: '确认使用此目录' })).toBeTruthy();
    await user.click(within(plan).getByRole('button', { name: '返回' }));
    const restored = await screen.findByRole('dialog', { name: '添加域名' });
    expect((within(restored).getByPlaceholderText('go.example.com') as HTMLInputElement).value).toBe('https://WWW.example.com/path');
    expect(within(restored).getByText('确认后可接入')).toBeTruthy();
    await user.click(within(restored).getByRole('button', { name: '查看接入计划' }));
    await user.click(within(await screen.findByRole('dialog', { name: '添加 www.example.com' })).getByRole('button', { name: '确认使用此目录' }));
    expect(await screen.findByText(/现在可以创建第一条短链接/)).toBeTruthy();
    expect(applyPayloads).toHaveLength(1);
    expect(applyPayloads[0].acknowledgeDomainTakeover).toBe(true);
  });

  it('blocks the same managed host even when a different prefix is entered', async () => {
    const user = userEvent.setup();
    render(<App />);
    await screen.findByRole('heading', {name:'短链接'});
    await user.click(screen.getByRole('button', { name: /^域名管理$/ }));
    await user.click(screen.getByRole('button', { name: '添加域名' }));
    const editor = screen.getByRole('dialog', { name: '添加域名' });
    await user.clear(within(editor).getByPlaceholderText('go.example.com'));
    await user.type(within(editor).getByPlaceholderText('go.example.com'), 'go.example.com');
    const prefix = within(editor).getByLabelText(/链接目录/);
    await user.clear(prefix);
    await user.type(prefix, 'other');
    await user.click(within(editor).getByRole('button', { name: '检查并接入' }));
    expect(await within(editor).findByText('需要先处理')).toBeTruthy();
    expect(within(editor).getByText(/已使用 \/r\/ 目录/)).toBeTruthy();
    expect(within(editor).getByText(/一个主机名只能接入一个链接目录/)).toBeTruthy();
    expect(within(editor).getByText(/管理已有域名或更换主机名/)).toBeTruthy();
    expect(within(editor).queryByText(/请选择明确的账户/)).toBeNull();
    expect(within(editor).queryByRole('button', { name: '查看接入计划' })).toBeNull();
  });

  it('keeps the ordinary 404 path on the standard confirmation flow', async () => {
    const user = userEvent.setup();
    render(<App />);
    await screen.findByRole('heading', {name:'短链接'});
    await user.click(screen.getByRole('button', { name: /^域名管理$/ }));
    await user.click(screen.getByRole('button', { name: '添加域名' }));
    const editor = screen.getByRole('dialog', { name: '添加域名' });
    await user.type(within(editor).getByPlaceholderText('go.example.com'), 'unused.example.org');
    await user.click(within(editor).getByRole('button', { name: '检查并接入' }));
    await user.selectOptions(await within(editor).findByRole('combobox', { name: /选择账户与区域/ }), 'demo-a');
    await user.click(within(editor).getByRole('button', { name: '检查并接入' }));
    expect(await within(editor).findByText('可用')).toBeTruthy();
    await user.click(within(editor).getByRole('button', { name: '查看接入计划' }));
    const plan = await screen.findByRole('dialog', { name: '添加 unused.example.org' });
    expect(within(plan).getByRole('button', { name: '确认并执行' })).toBeTruthy();
    expect(within(plan).queryByText('请确认接管范围')).toBeNull();
  });

  it('discards an in-flight domain result after the draft changes', async () => {
    const originalDispatch = bridge.dispatch;
    let resolvePreparation: ((value: DomainPreparation) => void) | undefined;
    const mockedDispatch = (action: Action, payload?: Record<string, unknown>): Promise<unknown> => {
      if (action === 'prepare_domain') return new Promise<DomainPreparation>(resolve => { resolvePreparation = resolve; });
      return originalDispatch(action, payload);
    };
    vi.spyOn(bridge, 'dispatch').mockImplementation(mockedDispatch as typeof bridge.dispatch);
    const user = userEvent.setup();
    render(<App />);
    await screen.findByRole('heading', {name:'短链接'});
    await user.click(screen.getByRole('button', { name: /^域名管理$/ }));
    await user.click(screen.getByRole('button', { name: '添加域名' }));
    const editor = screen.getByRole('dialog', { name: '添加域名' });
    const input = within(editor).getByPlaceholderText('go.example.com');
    await user.type(input, 'old.example.org');
    await user.click(within(editor).getByRole('button', { name: '检查并接入' }));
    fireEvent.change(input, { target: { value: 'new.example.org' } });
    resolvePreparation?.({ host: 'old.example.org', prefix: 'r', candidates: [], checks: [{ label: '旧结果', ok: true, level: 'pass', message: '不应显示' }], canApply: false });
    await waitFor(() => expect((within(editor).getByRole('button', { name: '检查并接入' }) as HTMLButtonElement).disabled).toBe(false));
    expect(within(editor).queryByText('旧结果')).toBeNull();
    expect(within(editor).queryByText(/old\.example\.org/)).toBeNull();
  });
  it('navigates between four working pages', async () => {
    render(<App />);
    await screen.findByRole('heading', {name:'短链接'});
    fireEvent.click(screen.getByRole('button', { name: /^域名管理$/ }));
    expect(screen.getByRole('heading',{name:'域名管理'})).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: /^平台地址$/ }));
    expect(screen.getByRole('heading',{name:'平台地址'})).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: /^Cloudflare 账户$/ }));
    expect(screen.getByRole('heading',{name:'Cloudflare 账户'})).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: '检查更新' }));
    const update = await screen.findByRole('dialog', { name: '应用更新' });
    expect(within(update).getByText('更新渠道尚未启用。请使用正式发行渠道获取新版本。')).toBeTruthy();
  });

  it('shows and confirms a prepared plan before changing a link', async () => {
    render(<App />);
    await screen.findByRole('heading', {name:'短链接'});
    fireEvent.click(screen.getByRole('button', { name: '新建链接' }));
    const editor = screen.getByRole('dialog', { name: '创建短链接' });
    fireEvent.change(within(editor).getByPlaceholderText('例如 welcome'), { target: { value: 'campaign' } });
    fireEvent.change(within(editor).getByPlaceholderText('https://example.com/zh'), { target: { value: 'https://example.com/zh' } });
    fireEvent.change(within(editor).getByPlaceholderText('https://example.com/en'), { target: { value: 'https://example.org/en' } });
    fireEvent.click(within(editor).getByRole('button', { name: '下一步，核对内容' }));
    const plan = await screen.findByRole('dialog', { name: '保存短链接' });
    expect(within(plan).getByText('核对当前状态与资源归属')).toBeTruthy();
    expect(document.querySelector('.link-groups')?.textContent).not.toContain('/campaign');
    fireEvent.click(within(plan).getByRole('button', { name: '确认并执行' }));
    await waitFor(() => expect(screen.getByText('/campaign')).toBeTruthy());
    const test = await screen.findByRole('dialog', { name: '链接检测' });
    expect(within(test).getByText('等待生效')).toBeTruthy();
  });
  it('saves a pool reference with an independent code and preserves local unknown detection', async () => {
    render(<App />);
    await screen.findByRole('heading', {name:'短链接'});
    fireEvent.click(screen.getByRole('button', { name: /^平台地址$/ }));
    fireEvent.click(screen.getByRole('button', { name: '添加平台地址' }));
    const pool = screen.getByRole('dialog', { name: '添加平台地址' });
    fireEvent.change(within(pool).getByPlaceholderText('例如：常用平台 A'), {target:{value:'演示地址池'}});
    fireEvent.change(within(pool).getByPlaceholderText('https://example.com/join/'), {target:{value:'https://example.com/join/'}});
    fireEvent.change(within(pool).getByPlaceholderText('https://example.org/join/'), {target:{value:'https://example.org/join/'}});
    fireEvent.click(within(pool).getByRole('button', {name:'下一步，核对内容'}));
    let poolPlan = await screen.findByRole('dialog', {name:'保存平台地址'});
    expect(within(poolPlan).getByText(/关联链接：0 条；不会影响手动填写的链接/)).toBeTruthy();
    expect(within(poolPlan).getByText('官网链接：https://example.com/join/邀请码')).toBeTruthy();
    fireEvent.click(within(poolPlan).getByRole('button', {name:'返回'}));
    const restored = await screen.findByRole('dialog', {name:'添加平台地址'});
    expect((within(restored).getByPlaceholderText('例如：常用平台 A') as HTMLInputElement).value).toBe('演示地址池');
    fireEvent.click(within(restored).getByRole('button', {name:'下一步，核对内容'}));
    poolPlan = await screen.findByRole('dialog', {name:'保存平台地址'});
    fireEvent.click(within(poolPlan).getByRole('button', {name:'确认并执行'}));
    await waitFor(()=>expect(screen.getByText('演示地址池')).toBeTruthy());
    fireEvent.click(screen.getByRole('button', {name:/^短链接/}));
    fireEvent.click(screen.getByRole('button', {name:'新建链接'}));
    const editor = screen.getByRole('dialog', {name:'创建短链接'});
    fireEvent.change(within(editor).getByPlaceholderText('例如 welcome'), {target:{value:'pool-code'}});
    fireEvent.click(within(editor).getByRole('button', {name:'平台地址'}));
    fireEvent.change(within(editor).getByPlaceholderText('例如 member_01'), {target:{value:'member_01'}});
    fireEvent.click(within(editor).getByRole('button', {name:'下一步，核对内容'}));
    const linkPlan = await screen.findByRole('dialog', {name:'保存短链接'});
    expect(within(linkPlan).getByText('邀请码：member_01')).toBeTruthy();
    expect(within(linkPlan).queryByText(/中国大陆：https/)).toBeNull();
    fireEvent.click(within(linkPlan).getByRole('button', {name:'确认并执行'}));
    const result = await screen.findByRole('dialog', {name:'链接检测'});
    expect(within(result).getAllByText(/本地预览未发起网络检测/)).toHaveLength(2);
    fireEvent.click(within(result).getByRole('button', {name:'完成'}));
    expect(screen.getByText('暂时无法确认', {exact:false})).toBeTruthy();
    expect(screen.getByText('平台地址：演示地址池 · 邀请码：member_01')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', {name:/^平台地址$/}));
    fireEvent.click(screen.getByRole('button', {name:'编辑地址'}));
    const editPool = screen.getByRole('dialog', {name:'编辑平台地址'});
    fireEvent.change(within(editPool).getByPlaceholderText('https://example.org/join/'), {target:{value:'https://example.org/new/'}});
    fireEvent.click(within(editPool).getByRole('button', {name:'下一步，核对内容'}));
    const editPlan = await screen.findByRole('dialog', {name:'保存平台地址'});
    expect(within(editPlan).getByText('关联链接：1 条会一起更新')).toBeTruthy();
    fireEvent.click(within(editPlan).getByRole('button', {name:'确认并执行'}));
    await waitFor(()=>expect(screen.queryByRole('dialog', {name:'保存平台地址'})).toBeNull());
    fireEvent.click(screen.getByRole('button', {name:/^短链接/}));
    expect(screen.getByText('结果已过期', {exact:false})).toBeTruthy();
    expect(screen.getByText('平台地址：演示地址池 · 邀请码：member_01')).toBeTruthy();
  });
  it('prepares optional monitoring without displaying its secret in the plan', async () => {
    render(<App />);
    await screen.findByRole('heading', {name:'短链接'});
    fireEvent.click(screen.getByRole('button', {name:/^Cloudflare 账户$/}));
    fireEvent.click(screen.getByRole('button', {name:'管理 示例账户 · 团队'}));
    const manager = screen.getByRole('dialog', {name:'账户管理'});
    fireEvent.click(within(manager).getByRole('button', {name:'配置检测服务'}));
    const editor = screen.getByRole('dialog', {name:'配置检测服务'});
    fireEvent.change(within(editor).getByPlaceholderText('https://probe.example.com/check'), {target:{value:'https://probe.example.com/check'}});
    fireEvent.change(within(editor).getByLabelText(/服务密钥/), {target:{value:'top-secret-demo-12345678901234567890'}});
    fireEvent.click(within(editor).getByRole('button', {name:'预览启用计划'}));
    const plan = await screen.findByRole('dialog', {name:'启用检测服务'});
    expect(plan.textContent).not.toContain('top-secret-demo');
    expect(plan.textContent).toContain('https://probe.example.com/check');
    fireEvent.click(within(plan).getByRole('button', {name:'确认并执行'}));
    await waitFor(()=>expect(screen.getByText(/检测服务：已启用/)).toBeTruthy());
  });

  it('previews a pasted invitation link before filling an address and rejects ambiguous links', async () => {
    render(<App />);
    await screen.findByRole('heading', { name: '短链接' });
    fireEvent.click(screen.getByRole('button', { name: /^平台地址$/ }));
    fireEvent.click(screen.getByRole('button', { name: '添加平台地址' }));
    const editor = screen.getByRole('dialog', { name: '添加平台地址' });
    const full = within(editor).getByRole('textbox', { name: '官网链接 完整邀请链接' });
    fireEvent.change(full, { target: { value: 'https://example.com/join/ONE?ref=TWO' } });
    fireEvent.click(within(editor).getAllByRole('button', { name: '识别' })[0]);
    expect(within(editor).getByRole('alert').textContent).toContain('邀请码位置不明确');
    expect((within(editor).getByPlaceholderText('https://example.com/join/') as HTMLInputElement).value).toBe('');
    fireEvent.change(full, { target: { value: 'https://example.com/register?lang=zh&ref=CODE_1&utm=sample' } });
    fireEvent.click(within(editor).getAllByRole('button', { name: '识别' })[0]);
    expect(within(editor).getByText('CODE_1')).toBeTruthy();
    fireEvent.click(within(editor).getByRole('button', { name: '填入链接地址' }));
    expect((within(editor).getByPlaceholderText('https://example.com/join/') as HTMLInputElement).value).toBe('https://example.com/register?lang=zh&ref=');
    expect((within(editor).getAllByPlaceholderText('例如 ?lang=zh')[0] as HTMLInputElement).value).toBe('&utm=sample');
    expect(within(editor).getByRole('button', { name: '下一步，核对内容' })).toBeTruthy();
  });
  it('lets valid manual addresses proceed when the optional paste helper contains incomplete text', async () => {
    render(<App />);
    await screen.findByRole('heading', { name: '短链接' });
    fireEvent.click(screen.getByRole('button', { name: /^平台地址$/ }));
    fireEvent.click(screen.getByRole('button', { name: '添加平台地址' }));
    const editor = screen.getByRole('dialog', { name: '添加平台地址' });
    fireEvent.change(within(editor).getByRole('textbox', { name: '官网链接 完整邀请链接' }), { target: { value: 'incomplete address' } });
    fireEvent.change(within(editor).getByPlaceholderText('例如：常用平台 A'), { target: { value: '示例平台' } });
    fireEvent.change(within(editor).getByPlaceholderText('https://example.com/join/'), { target: { value: 'https://example.com/join/' } });
    fireEvent.change(within(editor).getByPlaceholderText('https://example.org/join/'), { target: { value: 'https://example.org/join/' } });
    expect((within(editor).getByRole('textbox', { name: '官网链接 完整邀请链接' }) as HTMLInputElement).type).toBe('text');
    fireEvent.click(within(editor).getByRole('button', { name: '下一步，核对内容' }));
    expect(await screen.findByRole('dialog', { name: '保存平台地址' })).toBeTruthy();
  });
  it('fills the selected mainland address from an invitation link', async () => {
    render(<App />);
    await screen.findByRole('heading', { name: '短链接' });
    fireEvent.click(screen.getByRole('button', { name: /^平台地址$/ }));
    fireEvent.click(screen.getByRole('button', { name: '添加平台地址' }));
    const editor = screen.getByRole('dialog', { name: '添加平台地址' });
    fireEvent.click(within(editor).getByRole('button', { name: '添加大陆访问地址' }));
    const mainland = within(editor).getByRole('textbox', { name: '大陆访问地址（首选） 完整邀请链接' });
    fireEvent.change(mainland, { target: { value: 'https://example.com/join/CODE' } });
    fireEvent.click(within(editor).getAllByRole('button', { name: '识别' })[1]);
    fireEvent.click(within(editor).getByRole('button', { name: '填入链接地址' }));
    expect((within(editor).getAllByPlaceholderText('https://example.org/join/')[0] as HTMLInputElement).value).toBe('https://example.com/join/');
  });
});
